//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OAEntities : DbContext
    {
        public OAEntities()
            : base("name=OAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OA_AUTHORITY> OA_AUTHORITY { get; set; }
        public virtual DbSet<OA_BUDGET_TYPE> OA_BUDGET_TYPE { get; set; }
        public virtual DbSet<OA_CG> OA_CG { get; set; }
        public virtual DbSet<OA_CG_SUPP> OA_CG_SUPP { get; set; }
        public virtual DbSet<OA_CH_REL> OA_CH_REL { get; set; }
        public virtual DbSet<OA_FK> OA_FK { get; set; }
        public virtual DbSet<OA_HT> OA_HT { get; set; }
        public virtual DbSet<OA_HT_SUPP> OA_HT_SUPP { get; set; }
        public virtual DbSet<OA_MENU> OA_MENU { get; set; }
        public virtual DbSet<OA_OUR_OM_REL> OA_OUR_OM_REL { get; set; }
        public virtual DbSet<OA_PAYMENT> OA_PAYMENT { get; set; }
        public virtual DbSet<OA_PAYMENT_AUDIT> OA_PAYMENT_AUDIT { get; set; }
        public virtual DbSet<OA_PROCESS> OA_PROCESS { get; set; }
        public virtual DbSet<OA_RECORD> OA_RECORD { get; set; }
        public virtual DbSet<OA_SHIFT> OA_SHIFT { get; set; }
        public virtual DbSet<OA_USER> OA_USER { get; set; }
        public virtual DbSet<OA_USER_ROLE> OA_USER_ROLE { get; set; }
        public virtual DbSet<OA_USR_OUR_REL> OA_USR_OUR_REL { get; set; }
        public virtual DbSet<OA_YC_REL> OA_YC_REL { get; set; }
        public virtual DbSet<OA_YS> OA_YS { get; set; }
        public virtual DbSet<OA_YS_SUPP> OA_YS_SUPP { get; set; }
    
        public virtual int OA_GET_MYSQL_INFO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OA_GET_MYSQL_INFO");
        }
    }
}
