//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class OA_BUDGET_TYPE
    {
        public int OBT_ID { get; set; }
        public string OBT_NAME { get; set; }
        public string OBT_DESCRIPTION { get; set; }
        public string OBT_NUMBER { get; set; }
        public string OBT_DEPART { get; set; }
        public Nullable<double> OBT_SUM { get; set; }
        public Nullable<System.DateTime> OBT_CREATE_DATE { get; set; }
        public string OBT_NOTE { get; set; }
        public string OBT_YEAR { get; set; }
        public string OBT_ENABLE { get; set; }
        public string OBT_RECORDER { get; set; }
    }
}
