//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class OA_CG_SUPP
    {
        public int CGS_RUN_ID { get; set; }
        public string CGS_CURRENT_STEP { get; set; }
        public string CGS_RECEIVE_DATE { get; set; }
        public string CGS_CHECK_DATE { get; set; }
        public string CGS_PAY_DATE { get; set; }
        public string CGS_NOTE { get; set; }
    }
}
