//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class OA_CG
    {
        public int CG_RUN_ID { get; set; }
        public string CG_TITLE { get; set; }
        public string CG_SEQ { get; set; }
        public Nullable<System.DateTime> CG_DATE { get; set; }
        public string CG_NAME { get; set; }
        public string CG_CREATE_DEP { get; set; }
        public string CG_MODE { get; set; }
        public string CG_TYPE { get; set; }
        public string CG_SUM { get; set; }
        public string CG_HAVE_HT { get; set; }
        public string CG_NOTE1 { get; set; }
        public string CG_NOTE2 { get; set; }
        public string CG_CREATER { get; set; }
        public string CG_COMPANY { get; set; }
        public string CG_APPROVAL_DATE { get; set; }
        public string CG_DETAILS { get; set; }
        public string CG_DELIVERY_DATE { get; set; }
    }
}
