//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class OA_FK
    {
        public int FK_RUN_ID { get; set; }
        public string FK_TITLE { get; set; }
        public string FK_SEQ { get; set; }
        public Nullable<System.DateTime> FK_DATE { get; set; }
        public string FK_CREATE_DEP { get; set; }
        public string FK_CREATER { get; set; }
        public string FK_COMPANY { get; set; }
        public string FK_PAY_DATE { get; set; }
        public string FK_PAY_TYPE { get; set; }
        public string FK_MONEY_TYPE { get; set; }
        public string FK_TOTAL_SUM { get; set; }
        public string FK_PAY_SUM { get; set; }
        public string FK_DETAILS { get; set; }
    }
}
