//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class OA_HT
    {
        public int HT_RUN_ID { get; set; }
        public string HT_TITLE { get; set; }
        public string HT_SEQ { get; set; }
        public Nullable<System.DateTime> HT_DATE { get; set; }
        public string HT_NAME { get; set; }
        public string HT_COMPANY { get; set; }
        public string HT_CREATE_DEP { get; set; }
        public string HT_SUM { get; set; }
        public string HT_MONEY_TYPE { get; set; }
        public string HT_SERIAL_NUM { get; set; }
        public string HT_CREATER { get; set; }
        public string HT_APPROVAL_DATE { get; set; }
        public string HT_VALIDITY_DATE { get; set; }
    }
}
