//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class OA_PAYMENT_AUDIT
    {
        public int OPA_OP_ID { get; set; }
        public string OPA_TYPE { get; set; }
        public Nullable<System.DateTime> OPA_DATE { get; set; }
        public string OPA_NOTE { get; set; }
        public string OPA_RECORDER { get; set; }
        public Nullable<System.DateTime> OPA_RECORDTM { get; set; }
    }
}
