//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class OA_PROCESS
    {
        public int OP_RUN_ID { get; set; }
        public string OP_USER_NAME { get; set; }
        public string OP_STATUS { get; set; }
        public string OP_STEP { get; set; }
        public Nullable<System.DateTime> OP_RECIVE_TM { get; set; }
        public Nullable<System.DateTime> OP_DILIVER_TM { get; set; }
    }
}
