//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class OA_PAYMENT
    {
        public int OP_ID { get; set; }
        public Nullable<int> OP_RUN_ID { get; set; }
        public string OP_NAME { get; set; }
        public string OP_COMPANY_NAME { get; set; }
        public string OP_TYPE { get; set; }
        public Nullable<System.DateTime> OP_DATE { get; set; }
        public Nullable<int> OP_SUM { get; set; }
        public string OP_MONEY_TYPE { get; set; }
        public string OP_NOTE { get; set; }
        public string OP_CREATER { get; set; }
        public Nullable<System.DateTime> OP_RECODETM { get; set; }
        public string OP_ISAUDIT { get; set; }
    }
}
