//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class OA_RECORD
    {
        public int OR_ID { get; set; }
        public string OR_NAME { get; set; }
        public string OR_NOTE { get; set; }
        public Nullable<System.DateTime> OR_DATE { get; set; }
        public string OR_NOTE2 { get; set; }
    }
}
