//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class OA_YS
    {
        public int YS_RUN_ID { get; set; }
        public string YS_TITLE { get; set; }
        public string YS_SEQ { get; set; }
        public Nullable<System.DateTime> YS_DATE { get; set; }
        public string YS_NAME { get; set; }
        public string YS_SERIAL_NUM { get; set; }
        public string YS_CREATE_DEP { get; set; }
        public string YS_ACCEPT_DEP { get; set; }
        public string YS_SUM { get; set; }
        public string YS_CREATER { get; set; }
        public string YS_APPROVAL_DATE { get; set; }
        public string YS_ACUM_SUM { get; set; }
        public string YS_TOTAL_SUM { get; set; }
        public string YS_DETAILS { get; set; }
    }
}
